# 站点 设置
title: 个人博客
SEOTitle: 博客 | 李先生
header-img: img/home-bg.jpg
keyword: "Java, MySQL, Linux, Docker, Redis, Nginx, Mongo, JavaScript"
description: "书到用时方恨少，肉到肥时方恨多。"

baseurl: ""

# 侧边栏 设置
sidebar-avatar: /img/avatar.jpg

# Build 设置
permalink: pretty
paginate: 10
exclude: ["less"]

# Gems 设置
gems: [jekyll-paginate]

# Markdown 设置
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM                            # use Github Flavored Markdown !important
